-- ~/.config/hypr/hyprland.lua
--
-- Hyprland 0.56+ Lua config, migrated from the niri config at
-- dotfiles/niri/config.kdl. The niri config is the source of truth: wherever
-- the old hyprland.conf and config.kdl disagreed on a keybind or a default
-- app, the niri value won. hyprland.conf survives only as a source of
-- Hyprland-specific bits (mouse binds, window rules, per-device input).
--
-- The layout is `scrolling`, Hyprland's native niri-alike: an infinitely
-- growing horizontal tape of columns. See lua/layout.lua.
--
-- Docs: https://wiki.hypr.land/Configuring/Start/
-- API:  /usr/share/hypr/stubs/hl.meta.lua  (authoritative, autogenerated)

-- ---------------------------------------------------------------------------
-- Module path bootstrap
-- ---------------------------------------------------------------------------
-- The wiki documents bare `require("myColors")`, which implies the config dir
-- is already on package.path. That is not guaranteed anywhere, so seed it
-- explicitly and idempotently. This makes `require("input")` etc. work
-- regardless of Hyprland's internal Lua state.

local configDir = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr"

local function addPath(p)
  if not string.find(package.path, p, 1, true) then
    package.path = p .. ";" .. package.path
  end
end

addPath(configDir .. "/lua/?.lua")
addPath(configDir .. "/lua/?/init.lua")

-- Exported for modules that need to reference files on disk (scripts, etc).
HYPR_CONFIG_DIR = configDir

-- ---------------------------------------------------------------------------
-- Modules
-- ---------------------------------------------------------------------------
-- Order matters a little: `look` and `layout` set config values that `binds`
-- and `rules` assume are already in place.

require("monitors")   -- hl.monitor()         - outputs, modes, positions
require("look")       -- hl.config()          - general / decoration / blur / anims / cursor
require("layout")     -- hl.config()          - scrolling, groups (tabs), per-ws layout
require("workspaces") -- hl.workspace_rule()  - per-monitor workspace blocks
require("input")      -- hl.config()          - keyboard / touchpad / devices / gestures
require("rules")      -- hl.window_rule()     - window + layer rules
require("binds")      -- hl.bind()            - keybinds
require("autostart") -- hl.on("hyprland.start")
